import Head from 'next/head'
import styles from '@/styles/2N.module.css'
import BottomNav from '@/Components/NavBarBottom'
import BarChart from '@/Components/BarChart/BarChart2.js'
import Link from 'next/link'

export default function TwoN() {
  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoholder}>
          <div>
            <img src="/LogoHorizontalWhite.svg" className={styles.logo}/>
          </div>
        </div>

        <div className={styles.contentContainer}>
          <h1 className={styles.h3}>Impact of Frauds This Year</h1>
          <div className={styles.container}>
            <BarChart/>
          </div>
          <div className={styles.description}>
                <p>While law enforcement agencies and members of the Fraud Prevention Forum are committed to strategically collaborating and dedicating resources to preventing and combatting fraud, Canadian consumers and businesses also have a huge role to play to help stop fraudsters. Education and awareness are the strongest line of defence against scams and fraud.</p>
                <p>If you or someone you know is a victim of a fraud, contact your local police service to report the crime and also report it to the Canadian Anti-Fraud Centre online or toll-free at 1-888-495-8501. If a financial loss did not occur, still report it to the Canadian Anti-Fraud Centre. If you have information about deceptive marketing practices, report it to the Competition Bureau. Your reports are essential to identify linkages, catch criminals, and prevent further victimization.</p>
          </div>
          <div className={styles.buttoncontainer}>
            <Link href="/FactThree"><button className={styles.button}><h4>Next Fact</h4></button></Link>
          </div>
        </div>
        <BottomNav/>
      </main>
    </>
  )
}

