import Head from 'next/head'
import styles from '@/styles/2O.module.css'
import BottomNav from '@/Components/NavBarBottom'
import BarChart from '@/Components/BarChart/BarChart3'
import Link from 'next/link'

export default function TwoO() {
  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoholder}>
          <div>
            <img src="/LogoHorizontalWhite.svg" className={styles.logo}/>
          </div>
        </div>

        <div className={styles.contentContainer}>
          <h1 className={styles.h3}>Fraud Losses This Year</h1>
          <div className={styles.container}>
            <BarChart/>
          </div>
          <p className={styles.description}>In 2022, the Canadian Anti-Fraud Centre received fraud and cybercrime reports totalling a staggering $530 million in victim losses. Nearly a 40% increase from the unprecedented $380 million in losses in 2021</p>
          <div className={styles.buttoncontainer}>
            <Link href="/FactFour"><button className={styles.button}><h4>Next Fact</h4></button></Link>
          </div>
        </div>
        <BottomNav/>
      </main>
    </>
  )
}

