import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import BottomNav from '@/Components/NavBarBottom'
import OneA from '@/Components/1A'
import HomePage from '@/Components/HomePage'
import TwoF from '@/Components/2F'
import TwoH from '@/Components/2H'
import TwoI from '@/Components/2I'
import TwoJ from '@/Components/2J'
import TwoK from '@/Components/2K'
import TwoG from '@/Components/2G'



export default function Home() {
  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <TwoG/>
      </main>
    </>
  )
}

