import Head from 'next/head'
import styles from '@/styles/1E.module.css'
import BottomNav from '@/Components/NavBarBottom'
import Link from 'next/link'


export default function OneE() {
  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
      <div className={styles.logoholder}>
                   <div>
                    <img src="/LogoHorizontalWhite.svg" className={styles.logo}/>
                   </div>
               </div>

               <div className={styles.contentContainer}>
                <div className={styles.container}>
                    <div className={styles.alertcont}>
                        <img src="/CheckMark.svg" className={styles.check}/>
                        <h3 className={styles.h3}>
                            Congratulations! You are not being scammed. :)
                        </h3>
                        <img src="/Mascot.svg" className={styles.mascot}/>
                    </div>
                </div>
                <div className={styles.buttoncontainer}>
                  <Link href="/"><button className={styles.button}><h4>Run Test Again</h4></button></Link>
                  <Link href="/reiterationpage"><button className={styles.button}><h4>Check What You Chose to as to Why You're Not Being Scammed</h4></button></Link> 
                </div>
               </div>
               <BottomNav/>
      </main>
    </>
  )
}

