import Head from 'next/head'
import styles from '@/styles/2F.module.css'
import BottomNav from '@/Components/NavBarBottom'

export default function TwoF() {
  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoholder}>
          <div>
            <img src="/LogoHorizontalWhite.svg" className={styles.logo}/>
          </div>
        </div>

        <div className={styles.contentContainer}>
          <h1 className={styles.h3}>Phone Call Scams</h1>
          <div className={styles.scrollbar}>
          <h3>
            Someone might pretend to be the government, your bank, your employer, someone that you owe money to, or even an old friend. Scammers use phone calls, emails, or fake websites to trick you into sharing your personal information. These tricks are sometimes called phishing. <br></br> The scammers then use your information to apply for credit cards, bank loans, and other kinds of credit. They can take money from your bank accounts and shop with your credit cards. This is sometimes called identity theft. <br></br> If you receive telephone calls from collection agencies or creditors for accounts that you do not have or purchases that you didn't make, you might be a victim of identity theft. Also, your bank or other financial statements might show withdrawals, transactions, or transfers that you didn't make. If you find that someone has used your identity, there are a few things you should do as soon as possible.
            <div className={styles.contentContainer2}>
              <ul className={styles.list}>
                <li>Report the identity theft to the police.</li>
                <li>Contact the financial institutions, credit card issuers, or companies that are involved.</li>
                <li>Report the identity theft to the Canadian Anti-Fraud Centre (CAFC).</li>
                <li>Cancel any missing identification.</li>
                <li>Contact the credit reporting agencies, Equifax and TransUnion.</li>
              </ul>
            </div>
          </h3>
        </div>
      </div>
      <BottomNav/>
      </main>
    </>
  )
}

