import Head from 'next/head'
import styles from '@/styles/1M.module.css'
import BottomNav from '@/Components/NavBarBottom'
import Link from 'next/link'
import { useContext } from 'react'
import { UserSelectionsContext } from './data'
import React, { useState } from 'react';
import Overlay from '@/Components/Popup/popup1'


var yes = process.env.NEXT_PUBLIC_YES;
var no = process.env.NEXT_PUBLIC_NO;


export default function OneM() {

  const [overlayOpen, setOverlayOpen] = useState(false);
  const [showCloseButton, setShowCloseButton] = useState(false);

  const handleOpenOverlay = () => {
    setOverlayOpen(true);
    setShowCloseButton(true);
  };

  const handleCloseOverlay = () => {
    setOverlayOpen(false);
    setShowCloseButton(false);
  };

  const handleShowCloseButton = () => {
    setShowCloseButton(true);
  };

  
  const { updateSelections } = useContext(UserSelectionsContext)

  const handleNoClick = () => {
    updateSelections('Is the message telling you that you won a prize or some form of reward that you can claim?', 'No')
  }

  const handleYesClick = () => {
    updateSelections('Is the message telling you that you won a prize or some form of reward that you can claim?', 'Yes')
  }



  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoholder}>
          <div>
            <img src="/LogoHorizontalWhite.svg" className={styles.logo}/>
          </div>
        </div>
        <div className={styles.contentContainer}>
          <div className={styles.container}>
            <h3 className={styles.h3}>
              Is the message telling you that you won a prize or some form of reward that you can claim?
            </h3>
          </div>
          <div className={styles.buttoncontainer}>
            <Link href="/Organization"><button className={styles.button} onClick={handleYesClick}><h4>{yes}</h4></button></Link>
            <Link href="/ScanVirus"><button className={styles.button} onClick={handleNoClick}><h4>{no}</h4></button></Link>
          </div>
        </div>


        <div>
          {!showCloseButton && (
            <button className={styles.overlayButton} onClick={handleOpenOverlay}>Examples</button>
          )}
          {overlayOpen && (
            <Overlay imageSrc="../Prizesscamemail.jpg" onClose={handleCloseOverlay} />
          )}
          {showCloseButton && (
            <button className={styles.closer} onClick={handleCloseOverlay}>Close</button>
          )}
        </div>

        <BottomNav/>
      </main>
    </>
  )
}

