import { useContext } from 'react'
import { UserSelectionsContext } from './data'
import Head from 'next/head'
import styles from '@/styles/Reiteration.module.css'
import BottomNav from '@/Components/NavBarBottom'
import HomePage from '@/Components/HomePage'

export default function Reiteration() {
  const { selections } = useContext(UserSelectionsContext)

  return (
    <>
      <Head>
        <title>Swindle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Layer_1(3).svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {selections['What type of scam are you trying to check?'] && (
            <>
              <h3 className={styles.h3}>What type of scam are you trying to check?</h3>
              <p className={styles.answer}>{selections['What type of scam are you trying to check?']}</p>
            </>
          )}

          {selections['Have you provided any personal information?'] && (
            <>
              <h3 className={styles.h3}>Have you provided any personal information?</h3>
              <p className={styles.answer}>{selections['Have you provided any personal information?']}</p>
            </>
          )}

          {selections['What type of personal info was it asking for?'] && (
            <>
              <h3 className={styles.h3}>What type of personal info was it asking for?</h3>
              <p className={styles.answer}>{selections['What type of personal info was it asking for?']}</p>
            </>
          )}

          {selections['Is this message asking you to go to a link?'] && (
            <>
              <h3 className={styles.h3}>Is this message asking you to go to a link?</h3>
              <p className={styles.answer}>{selections['Is this message asking you to go to a link?']}</p>
            </>
          )}

          {selections['Are they asking for money?'] && (
            <>
              <h3 className={styles.h3}>Are they asking for money?</h3>
              <p className={styles.answer}>{selections['Are they asking for money?']}</p>
            </>
          )}

          {selections['Is this message from a person or an organization you have seen or used before?'] && (
            <>
              <h3 className={styles.h3}>Is this message from a person or an organization you have seen or used before?</h3>
              <p className={styles.answer}>{selections['Is this message from a person or an organization you have seen or used before?']}</p>
            </>
          )}

          {selections['Does the link look like it is from something familiar or legitimate?'] && (
            <>
              <h3 className={styles.h3}>Does the link look like it is from something familiar or legitimate?</h3>
              <p className={styles.answer}>{selections['Does the link look like it is from something familiar or legitimate?']}</p>
            </>
          )}

          {!Object.keys(selections).length && (
            <HomePage message="You haven't answered any questions yet. Please take the quiz first." />
          )}

          <BottomNav />
        </div>
      </main>
    </>
  )
}
